# Assessment Samples

The following assignments are opportunities for learners to demonstrate their understanding of the course outcomes.  Please confirm assignment details with your instructor, referring to the course syllabus.

Note that Assignment dropboxes are located in Moodle.  Also refer to the Course Schedule in Moodle for the specific due dates.


## Assignment: Company Website Analysis {-}
```{block, type='assessment'}
Investigate the Human Resources or Faculty Development portion of a company's website, a higher education institution or adult learning facility, preferably one with which you are familiar. Focus on the faculty or employee development part of the website. In this assignment, you will apply the theory of teaching in/for/with depth by analyzing the learning culture of an organization.

In a 4-5 page APA formatted paper, analyze the website by responding to the following questions in your report:

1.	What can you infer about the company’s learning culture?
2.	From what is visible on the public website, would you say it is an authentic learning community? Why or why not? Discuss whether the website reflects aspects of one or more of the learning community models explored in previous lessons.
3.	Do you see evidence that interconnectedness and integrity are valued?  Explain.
4.	What traits and skills seem to be valued in employees?
5.	How does the company develop skills in its employees (e.g., workshops, seminars, mentoring)? Are the methods based on the principles of andragogy? (see Smith YouTube video). What specific adult learning strategies do you see reflected in the development/training opportunities for employees?

Your paper should be 4-5 pages and should incorporate references to at least five scholarly sources you have studied in this course, or other scholarly sources you have identified.

The paper should include:

1.	Introduction
2.	Analysis (responding to the prompts)
3.	Conclusion
4.	Reference List
```

 ```{block, type='caution'}
Note: We're still looking for an accessible rubric format. In the meantime, we've listed the criteria as follows to help those with screen readers.
```

### Company Website Analysis Rubric {-}
See the following rubric that explains how your assignment will be evaluated. Also available as a [pdf](assets/assessment/Company-Website-Analysis-RUBRIC.pdf)

#### APA Formatting {-}

**Unsatisfactory:** Paper does not model language and conventions used in scholarly literature.
Writing is not well-organized. Several errors in grammar or composition. Sources
are not cited. APA citations are not appropriately formatted.

**Developing:** Paper partially models language and conventions used in scholarly literature.
Writing is somewhat well organized and includes some errors in grammar or
composition. Not all sources cited. APA citations are generally formatted
correctly, with several errors.

**Proficient:** *Paper consistently models language and conventions used in scholarly
literature. Writing is well-organized and includes few (if any) errors in
grammar or composition. All resources are appropriately cited (including in-text
citations and bibliography information). Few (if any) errors in APA citations.*

**Exemplary:** Paper is an exemplar of language and conventions used in scholarly literature.
Writing is well-organized and free of errors in grammar or composition. All
resources are appropriately cited. No errors in APA format.

#### DEVELOPING a COHESIVE and LOGICAL ACADEMIC ARGUMENT {-}

**Unsatisfactory:** Does not make a focused, cohesive, or logical academic argument. Paper is
confusing, and is missing an introduction, body, or conclusion. Transitions
between sections and ideas are missing.

**Developing:** Makes an academic argument that is only partially focused, cohesive and logical.
Paper is generally organized, but is missing an introduction, body, or
conclusion. Transitions between sections and ideas are unclear.

**Proficient:** *Makes a focused, cohesive, logical academic argument. Paper is effectively
organized and includes an introduction, body, and conclusion. Transitions
between sections and ideas are clear.*

**Exemplary:** Makes a focused, cohesive, logical and compelling academic argument. Paper is
effectively organized and includes an introduction, body, and conclusion.
Transitions between sections and ideas are clear and build on each other.

#### ANALYSIS of LEARNING CULTURE {-}

**Unsatisfactory:** Does not include an analysis of the company learning culture, and no evaluation
of the authenticity of the learning community.

**Developing:** Includes a partial analysis of the company learning culture, including a limited
evaluation of the authenticity of the learning community.

**Proficient:** *Includes a detailed analysis of the company learning culture, including an
evaluation of the authenticity of the learning community.*

**Exemplary:** Includes a detailed analysis of the company learning culture, including an
evaluation of the authenticity of the learning community. Includes a thoughtful
analysis, integrating scholarly literature to support analysis and furthering
scholarly thinking related to teacher identity.

#### EVALUATION of INTERCONNECTEDNESS and INTEGRITY {-}
**Unsatisfactory:** Does not include an evaluation of evidence of interconnectedness and integrity
on the company website. Does not integrate scholarly sources in the evaluation.

**Developing:** Includes a partial evaluation of evidence of interconnectedness and integrity on
the company website. Evaluation includes only limited reference to scholarly
sources.

**Proficient:** *Includes a detailed evaluation of evidence of interconnectedness and integrity
on the company website. Evaluation integrates scholarly sources.*

**Exemplary:** Includes a detailed evaluation of evidence of interconnectedness and integrity
on the company website. Includes recommendations for ways in which to integrate
interconnectedness and integrity into employee development.

#### ANALYSIS of ADULT LEARNING STRATEGIES {-}

**Unsatisfactory:** Does not include a detailed analysis of valued skills and evidence of adult
learning theory in employee development. Does not integrate scholarly sources.

**Developing:** Includes a partial analysis of valued skills and evidence of adult learning
theory in employee development. Analysis integrates few, if any, scholarly
sources.

**Proficient:** *Includes a detailed analysis of valued skills and evidence of adult learning
theory in employee development. Analysis integrates scholarly sources.*

**Exemplary:** Includes a detailed analysis of valued skills and evidence of adult learning
theory in employee development. Includes recommendations for ways in which to
integrate adult learning theory into employee development.

#### SCHOLARLY INTEGRATION {-}

**Unsatisfactory:** Does not integrate scholarly references to support claims and assertions made in
the paper.

**Developing:** Integrates scholarly references to support some of the claims and assertions
made in the paper.

**Proficient:** *Integrates scholarly references to support claims and assertions made in the
paper.*

**Exemplary:** Integrates scholarly references to support claims and assertions made in the
paper, effectively synthesizing different perspectives and research results from
scholarly sources.


|**TOTAL**|**0 = 0% (F)**|**10 = 50% (C)**|**15 = 75 (B)**|**20 = 100% (A+)**|
|---|---|---|---|---|
---
